# Generated by Django 5.2.11 on 2026-08-21 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilPrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metier', models.CharField(help_text='Ex : Coiffeur, Consultant, Kinésithérapeute', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('valide', models.BooleanField(default=False, help_text='Coché par un administrateur après vérification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_prestataire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_reserve', models.BooleanField(default=False)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='rendezvous.profilprestataire')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('prestataire', 'date', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='rendezvous.profilprestataire')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_pris', to=settings.AUTH_USER_MODEL)),
                ('disponibilite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='rendezvous.disponibilite')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendezvous.service')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
