# Generated by Django 5.2.11 on 2026-08-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilite',
            options={'ordering': ['date', 'heure_debut'], 'verbose_name': 'Disponibilité', 'verbose_name_plural': 'Disponibilités'},
        ),
        migrations.AlterModelOptions(
            name='profilprestataire',
            options={'verbose_name': 'Profil Prestataire', 'verbose_name_plural': 'Profils Prestataires'},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
    ]
