# Generated by Django 5.2.11 on 2026-08-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_alter_disponibilite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='disponibilite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='rendezvous.disponibilite'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué / Annulé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='rendezvous.rendezvous')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
